name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install client dependencies
        run: npm install
        working-directory: client
      - name: Build
        run: npm run build
        working-directory: client
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist